services:
  server:
    build: .
    volumes:
      - ./:/backend/
    command: ["fastapi", "dev", "app/main.py", "--host", "0.0.0.0"]
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      migrations:
        condition: service_completed_successfully

  migrations:
    build: .
    volumes:
      - ./:/backend/
    command: ["alembic", "upgrade", "head"]
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - 5432:5432

volumes:
  postgres_data:
