services:
  test:
    build: .
    volumes:
      - ./:/backend/
    command: "pytest -v"
    env_file:
      - .env
    environment:
      - POSTGRES_SERVER=db-test
    depends_on:
      - db-test

  db-test:
    image: postgres
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_TEST_DB}
