"""create tables

Revision ID: 721a2add7d84
Revises: 
Create Date: 2025-07-25 16:22:04.421837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '721a2add7d84'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hobbies',
                    sa.Column(
                        'name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_hobbies_name'), 'hobbies', ['name'], unique=False)
    op.create_table('users',
                    sa.Column(
                        'username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column(
                        'name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('password_hash',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email')
                    )
    op.create_index(op.f('ix_users_username'),
                    'users', ['username'], unique=True)
    op.create_table('user_hobbies',
                    sa.Column('interested', sa.Boolean(), nullable=False),
                    sa.Column('rating', sa.Integer(), nullable=True),
                    sa.Column('user_id', sa.Uuid(), nullable=False),
                    sa.Column('hobby_id', sa.Uuid(), nullable=False),
                    sa.ForeignKeyConstraint(['hobby_id'], ['hobbies.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('user_id', 'hobby_id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_hobbies')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_hobbies_name'), table_name='hobbies')
    op.drop_table('hobbies')
    # ### end Alembic commands ###
