"""cascade delete user_hobbies

Revision ID: 5930cc2ed8ec
Revises: 721a2add7d84
Create Date: 2025-08-14 12:16:54.812805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5930cc2ed8ec'
down_revision: Union[str, Sequence[str], None] = '721a2add7d84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('user_hobbies_user_id_fkey'),
                       'user_hobbies', type_='foreignkey')
    op.drop_constraint(op.f('user_hobbies_hobby_id_fkey'),
                       'user_hobbies', type_='foreignkey')
    op.create_foreign_key(op.f('user_hobbies_hobby_id_fkey'), 'user_hobbies',
                          'hobbies', ['hobby_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('user_hobbies_user_id_fkey'), 'user_hobbies',
                          'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('user_hobbies_user_id_fkey'),
                       'user_hobbies', type_='foreignkey')
    op.drop_constraint(op.f('user_hobbies_hobby_id_fkey'),
                       'user_hobbies', type_='foreignkey')
    op.create_foreign_key(op.f('user_hobbies_hobby_id_fkey'),
                          'user_hobbies', 'hobbies', ['hobby_id'], ['id'])
    op.create_foreign_key(op.f('user_hobbies_user_id_fkey'),
                          'user_hobbies', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
