"""unique hobby name

Revision ID: d3f2c17e19ae
Revises: 5930cc2ed8ec
Create Date: 2025-08-15 16:00:36.392757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd3f2c17e19ae'
down_revision: Union[str, Sequence[str], None] = '5930cc2ed8ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hobbies_name'), table_name='hobbies')
    op.create_index(op.f('ix_hobbies_name'), 'hobbies', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hobbies_name'), table_name='hobbies')
    op.create_index(op.f('ix_hobbies_name'), 'hobbies', ['name'], unique=False)
    # ### end Alembic commands ###
